name: Build APK

on:
  push:
    branches:
      - main  # Pas dit aan als je een andere branch gebruikt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Zorg ervoor dat dit overeenkomt met je project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug
        env:
          ANDROID_HOME: ${{ github.workspace }}/.android-sdk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: bin/*.apk
